# Generated by Django 4.0.3 on 2022-12-29 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fuel_delete_flag_fuel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
